### ISSUE TITLE
"Get and watch atomic swap lifecycle" fails

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#500]
There is a [CI fail on master](https://travis-ci.com/iov-one/iov-core/jobs/156630105) after [an unrelated change](https://github.com/iov-one/iov-core/compare/d34def4cd6ceb8...2875add6077d65):

```
1. Integration tests with bov+tendermint : Get and watch atomic swap lifecycle
   Expected $['7'] = 2 to equal 4.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:689:27
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
   Expected 'open' to equal 'claimed'.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:690:25
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
   Expected $['7'] = 4 to equal 3.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:691:28
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
   Expected $['7'] = 3 to equal 2.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:693:28
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
```

This smells like an indetermined order of results in

```ts
    const finalSwaps = await connection.getSwap({ recipient: rcptAddr });
    expect(finalSwaps.data.length).toEqual(3);
    const [open3, claim2, claim1] = finalSwaps.data;
```

**Comment by ethanfrey** [comment]
This is an ordering error, and looking at bnsconnection:getSwap, it seems we rely on the ordering of `tx_search` from tendermint.

It seems transactions may be sorted by the string value of their height rather than the integer value: https://github.com/tendermint/tendermint/issues/2759

I guess I need to sort it myself to ensure the ordering....
A bit hard to see the fix works as it doesn't happen continually.
