### ISSUE TITLE
Occasional CI fail "Get and watch atomic swap lifecycle"

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#556]
```
1. BnsConnection : Get and watch atomic swap lifecycle
   Expected 4 to equal 5.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:1376:25
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
   Expected 'open' to equal 'claimed'.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:1381:26
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
   Expected $['7'] = 4 to equal 3.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:1382:29
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
   Expected 'claimed' to equal 'open'.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:1383:26
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
   Expected $['7'] = 2 to equal 4.
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:1384:29
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
   TypeError: Cannot read property 'kind' of undefined
       at <Jasmine>
       at Object.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-bns/src/bnsconnection.spec.ts:1385:20
       at <Jasmine>
       at fulfilled /home/travis/build/iov-one/iov-core/packages/iov-bns/build/bnsconnection.spec.js:4:58
       at <Jasmine>
       at process._tickCallback internal/process/next_tick.js:189:7
```

https://travis-ci.com/iov-one/iov-core/jobs/160267270

**Comment by webmaster128** [comment]
Potentially fixed by bugfix in #557 but not sure

**Comment by webmaster128** [comment]
Not fixed, one more: https://travis-ci.com/iov-one/iov-core/jobs/161451669

**Comment by webmaster128** [comment]
Still exists in browser tests:

```
HeadlessChrome 0.0.0 (Linux 0.0.0) BnsConnection can start and watch an atomic swap lifecycle FAILED
	Error: Expected $['7'] = 6 to equal 8.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/bnsconnection.spec.js?:1294:31)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/bnsconnection.spec.js?:4:58)
	Error: Expected 'open' to equal 'claimed'.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/bnsconnection.spec.js?:1295:29)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/bnsconnection.spec.js?:4:58)
	Error: Expected $['7'] = 8 to equal 7.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/bnsconnection.spec.js?:1296:32)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/bnsconnection.spec.js?:4:58)
	Error: Expected $['7'] = 7 to equal 6.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/bnsconnection.spec.js?:1298:32)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/bnsconnection.spec.js?:4:58)
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 34 of 85 (1 FAILED) (skipped 1) (0 secs / 39.202 secs)
HeadlessChrome 0.0.0 (Linux 0.0.0) BnsConnection can start and watch an atomic swap lifecycle FAILED
	Error: Expected $['7'] = 6 to equal 8.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/bnsconnection.spec.js?:1294:31)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/bnsconnection.spec.js?:4:58)
	Error: Expected 'open' to equal 'claimed'.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/bnsconnection.spec.js?:1295:29)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/bnsconnection.spec.js?:4:58)
	Error: Expected $['7'] = 8 to equal 7.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/bnsconnection.spec.js?:1296:32)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/bnsconnection.spec.js?:4:58)
	Error: Expected $['7'] = 7 to equal 6.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/bnsconnection.spec.js?:1298:32)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/bnsconnection.spec.js?:4:58)
```

**Comment by webmaster128** [comment]
watchSwap() uses Stream.merge to merge `setTxs + delTxs` and `offers + releases`:

https://github.com/iov-one/iov-core/blob/a992b9f/packages/iov-bns/src/bnsconnection.ts#L397
https://github.com/iov-one/iov-core/blob/a992b9f/packages/iov-bns/src/bnsconnection.ts#L418

Both merge result are [sorted by the order of all incoming events](https://github.com/staltz/xstream#-mergestream1-stream2), which may not be deterministic. Maybe we want [stream concatenation](http://rxmarbles.com/#concat) in those places?

**Comment by webmaster128** [comment]
Still exists: https://travis-ci.com/iov-one/iov-core/jobs/172996390

**Comment by webmaster128** [comment]
This code

```
    const combiner = (evt: OpenSwap | SwapClaimTransaction | SwapTimeoutTransaction): BcpAtomicSwap => {
      switch (evt.kind) {
        case SwapState.Open:
          open.push(evt);
          return evt;
        default:
          // event is a swap claim/timeout, resolve an open swap and return new state
          const idx = open.findIndex(x => arraysEqual(x.data.id, evt.swapId));
          const done = this.context.settleAtomicSwap(open[idx], evt);
          open.splice(idx, 1);
          return done;
      }
    };
```

assumes that the open event comes before the claim/timeout event, which is not guaranted.
