### ISSUE TITLE
CI: RiseConnection liveTx : can listen to transactions by recipient address (transactions in history and updates) FAILED

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#728]
```
1. RiseConnection liveTx : can listen to transactions by recipient address (transactions in history and updates)
   Expected 1348595 to equal 1348596.
       at <Jasmine>
       at Object.next /home/travis/build/iov-one/iov-core/packages/iov-rise/src/riseconnection.spec.ts:767:40
       at Stream._n /home/travis/build/iov-one/iov-core/node_modules/xstream/src/index.ts:1092:22
       at RiseConnection.<anonymous> /home/travis/build/iov-one/iov-core/packages/iov-rise/src/riseconnection.ts:368:24
```

Test assums that two posted transactions make it into the same block, which is too optimistic.

* https://travis-ci.com/iov-one/iov-core/jobs/173127191

**Comment by webmaster128** [comment]
The whole idea of using two history transactions is worthless and error-prone. One from history and one from updates is sufficient.

**Comment by webmaster128** [comment]
Same issue here: https://travis-ci.com/iov-one/iov-core/jobs/173134552 When A and B are not in the same block it can take a long time for the test to finish
